IF EXISTS (SELECT name FROM sys.databases WHERE name = N'BbsDB')
BEGIN
    ALTER DATABASE BbsDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE BbsDB;
END
GO

CREATE DATABASE BbsDB;
GO

USE BbsDB;
GO

CREATE TABLE Posts (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    Message NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);
GO